// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.0.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:147

#ifndef _TAO_IDL_TIMEC_VPONYA_H_
#define _TAO_IDL_TIMEC_VPONYA_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from 
// be/be_visitor_root/root_ch.cpp:142
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_type.cpp:260

struct TimeOfDay;

typedef
  ::TAO_Fixed_Var_T<
      TimeOfDay
    >
  TimeOfDay_var;

typedef
  TimeOfDay &
  TimeOfDay_out;

// TAO_IDL - Generated from
// be/be_visitor_structure/structure_ch.cpp:49

struct  TimeOfDay
{

  // TAO_IDL - Generated from
  // be/be_type.cpp:306
  
  typedef TimeOfDay_var _var_type;
  typedef TimeOfDay_out _out_type;

  static void _tao_any_destructor (void *);
  
  ::CORBA::Short hour;
  ::CORBA::Short minute;
  ::CORBA::Short second;
};

// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_decl.cpp:39

extern  ::CORBA::TypeCode_ptr const _tc_TimeOfDay;

// TAO_IDL - Generated from
// be/be_interface.cpp:784

#if !defined (_TIME__VAR_OUT_CH_)
#define _TIME__VAR_OUT_CH_

class Time;
typedef Time *Time_ptr;

typedef
  TAO_Objref_Var_T<
      Time
    >
  Time_var;

typedef
  TAO_Objref_Out_T<
      Time
    >
  Time_out;

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ch.cpp:45

class  Time
  : public virtual ::CORBA::Object
{
public:
  friend class TAO::Narrow_Utils<Time>;

  // TAO_IDL - Generated from
  // be/be_type.cpp:306
  
  typedef Time_ptr _ptr_type;
  typedef Time_var _var_type;
  typedef Time_out _out_type;

  static void _tao_any_destructor (void *);

  // The static operations.
  static Time_ptr _duplicate (Time_ptr obj);

  static void _tao_release (Time_ptr obj);

  static Time_ptr _narrow (::CORBA::Object_ptr obj);
  static Time_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
  static Time_ptr _nil (void);

  virtual ::TimeOfDay get_gmt (void);

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:156

  virtual ::CORBA::Boolean _is_a (const char *type_id);
  virtual const char* _interface_repository_id (void) const;
  virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);

private:
  TAO::Collocation_Proxy_Broker *the_TAO_Time_Proxy_Broker_;

protected:
  // Concrete interface only.
  Time (void);

  // These methods traverse the inheritance tree and set the
  // parents piece of the given class in the right mode.
  virtual void Time_setup_collocation (void);

  // Concrete non-local interface only.
  Time (
      ::IOP::IOR *ior,
      TAO_ORB_Core *orb_core);
  
  // Non-local interface only.
  Time (
      TAO_Stub *objref,
      ::CORBA::Boolean _tao_collocated = false,
      TAO_Abstract_ServantBase *servant = 0,
      TAO_ORB_Core *orb_core = 0);

  virtual ~Time (void);

private:
  // Private and unimplemented for concrete interfaces.
  Time (const Time &);

  void operator= (const Time &);
};

// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_decl.cpp:39

extern  ::CORBA::TypeCode_ptr const _tc_Time;

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// be/be_visitor_root/root_ch.cpp:184

extern 
TAO::Collocation_Proxy_Broker *
(*_TAO_Time_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj);

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_TIME__TRAITS_)
#define _TIME__TRAITS_

  template<>
  struct  Objref_Traits< ::Time>
  {
    static ::Time_ptr duplicate (
        ::Time_ptr p);
    static void release (
        ::Time_ptr p);
    static ::Time_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Time_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:44


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, const TimeOfDay &); // copying version
 void operator<<= (::CORBA::Any &, TimeOfDay*); // noncopying version
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TimeOfDay *&); // deprecated
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, const TimeOfDay *&);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, Time_ptr); // copying
 void operator<<= (::CORBA::Any &, Time_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Time_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:45


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TimeOfDay &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, TimeOfDay &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:47

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Time_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, Time_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1590
#if defined (__ACE_INLINE__)
#include "timeC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

